<a href="https://colab.research.google.com/github/JAEHYEONG8121/Pytorch-Tutorial/blob/main/2_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TENSORS

- A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
- Similar To Numpy Arrays, but full of fun things that make them work beter on GPU's(vs regular CPU's).
- defualt data type of float32.
- More suitable for deep learning than a numpy array

In [6]:
import torch
import numpy as np

## LISTS

In [3]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

## NUMPY ARRAYS

In [7]:
np1 = np.random.rand(3, 4)
np1

array([[0.994551  , 0.40467964, 0.76717177, 0.63795056],
       [0.80234313, 0.12101565, 0.55099611, 0.3005335 ],
       [0.57873918, 0.18997725, 0.63035721, 0.61842479]])

In [8]:
np1.dtype

dtype('float64')

## TENSORS

In [14]:
tensor_2d = torch.randn(3, 4)
tensor_2d
#tensor_2d.dtype

tensor([[ 0.1681, -0.1012, -0.4331, -0.1524],
        [ 1.0155, -0.4001, -0.9665,  0.8647],
        [ 0.9373, -0.2001,  0.7461, -0.2166]])

In [11]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9946, 0.4047, 0.7672, 0.6380],
        [0.8023, 0.1210, 0.5510, 0.3005],
        [0.5787, 0.1900, 0.6304, 0.6184]], dtype=torch.float64)